name: Muse
version: '${project.version}'
main: mopskater.muse.Muse
author: MOPSKATER
api-version: 1.18

commands:
  musicianmode:
    usage: /<command>
    description: Toggle musician mode
    aliases: [mm]